site_name: Fast Craftsmanship
site_description: A CLI tool to accelerate project development using best practices
site_url: https://fguedes90.github.io/fast-craftsmanship/
repo_url: https://github.com/Fguedes90/fast-craftsmanship
repo_name: Fguedes90/fast-craftsmanship
use_directory_urls: true
strict: false

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/code-braces
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.share
  language: en
  favicon: assets/images/favicon.png
  include_search_page: true
  search_index_only: true

# Extras para o tema
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Fguedes90
  generator: false

# Extensions para Markdown
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - footnotes
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [fcship]
          options:
            show_source: true
            docstring_style: google

# Navegação
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Commands:
    - Overview: commands/index.md
    - GitHub: commands/github.md
    - Verify: commands/verify.md
    - Project: commands/project.md
    - Compact: commands/compact.md
    - DB: docs/cli/commands/db.md
    - Docs: docs/cli/commands/docs.md
    - Quality: docs/cli/commands/quality.md
    - Scaffold: docs/cli/commands/scaffold.md
    - Scraper: docs/cli/commands/scraper.md
    - VCS: docs/cli/commands/vcs.md
  - Functional Programming:
    - Introduction: functional/index.md
    - ROP: functional/rop.md
    - Effects: functional/effects.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - CLI:
      - Overview: docs/cli/index.md
      - Commands: docs/cli/commands/index.md
      - Utils:
        - Overview: docs/cli/utils/index.md
        - UI: docs/cli/utils/ui.md
    - Backend:
      - Overview: docs/backend/index.md
  - Dev Log:
    - Backend Planning:
      - Project Architecture: dev-log/backend-planing/01_project_archtecture.md
      - Architecture Analysis: dev-log/backend-planing/architecture_analysis.md
      - Architecture Decision Record: dev-log/backend-planing/architecture_decision_record.md
      - Architecture Verification: dev-log/backend-planing/architecture_verification.md
      - AST ROP Metric: dev-log/backend-planing/ast-rop-metric.md
      - Backend Plan: dev-log/backend-planing/backend-plan.md
      - Dependency Injection: dev-log/backend-planing/dependency_injection.md
      - Development Workflow: dev-log/backend-planing/development-workflow.md
      - Domain Driven Design: dev-log/backend-planing/domain_driven_design.md
      - Implementation Plan: dev-log/backend-planing/implementation-plan.md
      - Layer Boundaries: dev-log/backend-planing/layer_boundaries.md
      - Repository Patterns: dev-log/backend-planing/repository_patterns.md
    - CLI Fast Craftsmanship:
      - CLI and Snippets Plan: dev-log/cli-fast-craftsmanship/cli-and-snippets-plan.md