site_name: Fast Craftsmanship
site_description: A CLI tool to accelerate project development using best practices
site_url: https://fguedes90.github.io/fast-craftsmanship/
repo_url: https://github.com/Fguedes90/fast-craftsmanship
repo_name: Fguedes90/fast-craftsmanship
use_directory_urls: true
strict: false

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/code-braces
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.share
  language: en
  favicon: assets/images/favicon.png
  include_search_page: true
  search_index_only: true

# Extras para o tema
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Fguedes90
  generator: false

# JavaScript extra para Mermaid  
extra_javascript:
  - https://unpkg.com/mermaid@10.8.0/dist/mermaid.min.js
  - assets/js/mermaid-init.js

# Extensions para Markdown
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - footnotes
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [fcship]
          selection:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
              merge_init_into_class: true
              trim_doctest_flags: true
          rendering:
            show_root_heading: true
            show_root_full_path: true
            show_root_toc_entry: true
            show_category_heading: true
            show_source: true
            show_bases: true
            show_signature: true
            heading_level: 2
            members_order: source
            docstring_section_style: table
            merge_init_into_class: true
            show_if_no_docstring: false
            show_submodules: true
            group_by_category: true
            line_length: 100
            show_symbol_type_heading: true
            show_symbol_type_toc: true

# Navegação
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Commands:
    - Overview: commands/index.md
    - GitHub: commands/github.md
    - Verify: commands/verify.md
    - Project: commands/project.md
    - Compact: commands/compact.md
    - DB: docs/cli/commands/db.md
    - Docs: docs/cli/commands/docs.md
    - Quality: docs/cli/commands/quality.md
    - Scaffold: docs/cli/commands/scaffold.md
    - Scraper: docs/cli/commands/scraper.md
    - VCS: docs/cli/commands/vcs.md
  - Functional Programming:
    - Introduction: functional/index.md
    - ROP: functional/rop.md
    - Effects: functional/effects.md
    - Diagramas ROP: functional/diagrams.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Diagramas: development/diagrams.md
    - CLI:
      - Overview: docs/cli/index.md
      - Commands: docs/cli/commands/index.md
      - Utils:
        - Overview: docs/cli/utils/index.md
        - UI: docs/cli/utils/ui.md
    - Backend:
      - Overview: docs/backend/index.md
  - API:
    - Reference: api/reference.md
    - Guia de Docstrings: api/docstrings.md