name: CI

on:
  push:
    branches: [ main, develop, feat-cli-implementation ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install --upgrade pip
          uv pip install -e ".[dev]"
      - name: Lint with ruff
        run: |
          source .venv/bin/activate
          python -m ruff check fcship/
      - name: Test with pytest
        run: |
          source .venv/bin/activate
          python -m pytest tests/ --cov=fcship --cov-report=xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false